// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: add_qr_code.sql

package sqlc

import (
	"context"
)

const addQRCode = `-- name: AddQRCode :one
UPDATE urls
  SET qr_code = $1
  WHERE short_domain = $2
  RETURNING id, created_at, updated_at, hits, original_domain, short_domain, qr_code
`

type AddQRCodeParams struct {
	QrCode      []byte
	ShortDomain string
}

func (q *Queries) AddQRCode(ctx context.Context, arg AddQRCodeParams) (Url, error) {
	row := q.db.QueryRowContext(ctx, addQRCode, arg.QrCode, arg.ShortDomain)
	var i Url
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Hits,
		&i.OriginalDomain,
		&i.ShortDomain,
		&i.QrCode,
	)
	return i, err
}
