// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: create_url.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createNewURL = `-- name: CreateNewURL :one
INSERT INTO urls (id, created_at, updated_at, hits, original_domain, short_domain)
  VALUES ($1, $2, $3, 0, $4, $5)
  RETURNING id, created_at, updated_at, hits, original_domain, short_domain
`

type CreateNewURLParams struct {
	ID             uuid.UUID
	CreatedAt      time.Time
	UpdatedAt      time.Time
	OriginalDomain string
	ShortDomain    string
}

func (q *Queries) CreateNewURL(ctx context.Context, arg CreateNewURLParams) (Url, error) {
	row := q.db.QueryRowContext(ctx, createNewURL,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.OriginalDomain,
		arg.ShortDomain,
	)
	var i Url
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Hits,
		&i.OriginalDomain,
		&i.ShortDomain,
	)
	return i, err
}
