// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: delete_all_urls.sql

package sqlc

import (
	"context"
)

const deleteAllURLs = `-- name: DeleteAllURLs :exec
DELETE FROM urls
`

func (q *Queries) DeleteAllURLs(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllURLs)
	return err
}
