// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: get_url_via_short.sql

package sqlc

import (
	"context"
)

const getURLViaShortURL = `-- name: GetURLViaShortURL :one
SELECT original_domain FROM urls
  WHERE (short_domain = $1)
`

func (q *Queries) GetURLViaShortURL(ctx context.Context, shortDomain string) (string, error) {
	row := q.db.QueryRowContext(ctx, getURLViaShortURL, shortDomain)
	var original_domain string
	err := row.Scan(&original_domain)
	return original_domain, err
}
