// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: get_all_by_hits.sql

package sqlc

import (
	"context"
)

const getAllHitsDesc = `-- name: GetAllHitsDesc :many
SELECT original_domain, hits FROM urls
  ORDER BY hits DESC
`

type GetAllHitsDescRow struct {
	OriginalDomain string
	Hits           int32
}

func (q *Queries) GetAllHitsDesc(ctx context.Context) ([]GetAllHitsDescRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllHitsDesc)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllHitsDescRow
	for rows.Next() {
		var i GetAllHitsDescRow
		if err := rows.Scan(&i.OriginalDomain, &i.Hits); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
