name: ci

on:
  pull_request:
    branches: [main]

jobs:
  Tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.0"

      - name: Install gosec
        run: go install github.com/securego/gosec/v2/cmd/gosec@latest

      - name: Tests
        run: go test -cover ./...

      - name: Security checks
        run: gosec ./...

  Style:
    name: Style
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.0"

      - name: Install staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@latest

      - name: Fotrmatting
        run: test -z $(go fmt ./...)

      - name: Linting-1
        run: go fmt

      - name: Linting-2
        run: staticcheck
